services:
  ftpgrab:
    extends:
      service: ftpgrab
      file: "./ftpgrab/compose.yaml"
  mc:
    extends:
      service: mc
      file: "./mc/compose.yaml"

  ofelia:
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

configs:
  ftpgrab:
    name: ftpgrab
    file: "./ftpgrab/ftpgrab.yml"
  mc:
    name: mc
    file: "./mc/config.json"
  ofelia:
    name: ofelia
    file: "./ofelia/config.ini"

volumes:
  ftpgrab_db:
    name: ftpgrab_db
  ftpgrab_data:
    name: ftpgrab_data
