name: share-bak

services:
  ftpgrab:
    extends:
      service: ftpgrab
      file: "./ftpgrab/compose.yaml"
  mc:
    extends:
      service: mc
      file: "./mc/compose.yaml"
  ofelia:
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

volumes:
  ftpgrab_db:
    name: ftpgrab_db
  ftpgrab_data:
    name: ftpgrab_data

networks:
  ftpgrab:
    name: ftpgrab
