services:
  ofelia:
    image: mcuadros/ofelia
    restart: unless-stopped
    extra_hosts:
      - "shared.oncolog.ir=192.168.2.204"
    environment:
      TZ: "Asia/Tehran"
    networks:
      - ftpgrab
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config.ini:/etc/ofelia/config.ini:ro"
