services:
  ofelia:
    image: mcuadros/ofelia
    restart: unless-stopped
    environment:
      TZ: "Asia/Tehran"
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "config.ini:/etc/ofelia/config.ini:ro"
