services:
  mc:
    image: ${REGISTRY}/mc
    runtime: crun
    restart: always
    command: mirror --overwrite /var/ftpgrab_data/ oncolog/share-bak/
    configs:
      - source: mc
        target: /root/.mc/config.json
    network_mode: host
    volumes:
      - type: volume
        read_only: true
        source: ftpgrab_data
        target: /var/ftpgrab_data
