services:
  mc:
    image: minio/mc
    restart: unless-stopped
    entrypoint: tail
    command: -f /dev/null
    network_mode: host
    volumes:
      - "ftpgrab_data:/var/ftpgrab_data:ro"
      - "config.json:/root/.mc/config.json:ro"
