services:
  mc:
    image: minio/mc
    container_name: mc-share
    restart: unless-stopped
    entrypoint: tail
    command: -f /dev/null
    networks:
      - ftpgrab
    volumes:
      - "ftpgrab_data:/var/ftpgrab_data:ro"
      - "./config.json:/root/.mc/config.json:ro"
