services:
  ftpgrab:
    image: crazymax/ftpgrab
    container_name: ftpgrab
    restart: unless-stopped
    extra_hosts:
      - "shared.oncolog.ir=192.168.2.204"
    command: --config="/var/ftpgrab.yml" --schedule="0 */2 * * *"
    networks:
      - ftpgrab
    volumes:
      - "ftpgrab_db:/var/db"
      - "ftpgrab_data:/download"
      - "./ftpgrab.yml:/var/ftpgrab.yml:ro"
